_base_: PaddleSeg/configs/pp_liteseg/pp_liteseg_stdc1_hannasscapes_small_1024x512_scale0.5_160k.yml

weights: weights/ppliteseg_hannasscapes/model.pdparams

augment:
  aug_pred: True
  scales:  0.5
  flip_horizontal:  True
  flip_vertical:  True

slide:
  is_slide:  False
  crop_size:  None
  stride:  None

custom_color:  [255,0,0,20,120,40,255,255,0,0,0,255] #road,tree,building,sky
