batch_size: 2
iters: 80000

train_dataset:
  type: Dataset
  num_classes: 4
  dataset_root: /media/linx123-rtx/Elements/Drone_Vision_Datasets/Hannasscapes_small
  train_path: /media/linx123-rtx/Elements/Drone_Vision_Datasets/Hannasscapes_small/train_list.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  num_classes: 4
  dataset_root: /media/linx123-rtx/Elements/Drone_Vision_Datasets/Hannasscapes_small
  val_path: /media/linx123-rtx/Elements/Drone_Vision_Datasets/Hannasscapes_small/val_list.txt
  transforms:
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
